In [53]:
import pandas as pd
import numpy as numpy
import seaborn as sns
import matplotlib.pyplot as plt

In [54]:
df_dur = pd.read_csv("data/el_noktalariDur.csv")
df_başla = pd.read_csv("data/el_noktalariBaşla.csv")
df_geri = pd.read_csv("data/el_noktalariGeri.csv")
df_ileri = pd.read_csv("data/el_noktalariIleri.csv")

In [55]:
df_başla.head()

frame   x0   y0   z0         x1         y1        z1         x2  \
0    frame_0.jpg  0.0  0.0  0.0  20.921745 -32.013216 -0.004908  63.702908   
1    frame_1.jpg  0.0  0.0  0.0  25.215855 -33.129122 -0.005567  70.546875   
2   frame_10.jpg  0.0  0.0  0.0  21.059303 -51.856520 -0.004809  39.689026   
3  frame_100.jpg  0.0  0.0  0.0  20.542946 -48.255172 -0.003943  50.350914   
4  frame_101.jpg  0.0  0.0  0.0  21.442451 -48.781872 -0.003678  51.380196   

           y2        z2  ...       z17        x18        y18       z18  \
0  -63.090448 -0.011111  ... -0.029584  85.430202  36.061184 -0.031815   
1  -60.488298 -0.012280  ... -0.028890  89.014263  45.146148 -0.031010   
2 -102.589860 -0.008057  ... -0.018782  59.080753 -18.782566 -0.019961   
3  -82.153358 -0.008138  ... -0.007622  98.735275  31.494176 -0.005686   
4  -82.783248 -0.007359  ... -0.005646  99.460602  28.227761 -0.003660   

         x19        y19       z19        x20        y20       z20  
0  69.083805  34.941480 -0.025963  46.978397  30.403762 -0.022198  
1  72.302513  41.144013 -0.025329  50.641079  34.783959 -0.021769  
2  47.803574 -15.707209 -0.017838  31.267262 -13.266506 -0.017717  
3  88.978386  26.162224 -0.001247  77.652740  24.368598  0.001567  
4  90.144081  22.974086  0.000873  78.666000  22.793262  0.003747  

[5 rows x 64 columns]

In [56]:
df_başla.describe()

x0     y0     z0          x1          y1          z1          x2  \
count  445.0  445.0  445.0  445.000000  445.000000  445.000000  445.000000   
mean     0.0    0.0    0.0    4.635064  -41.398684   -0.005250    7.437587   
std      0.0    0.0    0.0   12.254285    7.067382    0.003155   34.017241   
min      0.0    0.0    0.0  -22.323017  -65.664210   -0.018138  -53.043823   
25%      0.0    0.0    0.0   -4.077015  -45.333667   -0.006618  -22.468185   
50%      0.0    0.0    0.0    4.183159  -40.042784   -0.005136    4.837303   
75%      0.0    0.0    0.0   15.078850  -36.732595   -0.003778   40.108337   
max      0.0    0.0    0.0   31.289291  -22.590230    0.009951   74.264946   

               y2          z2          x3  ...         z17         x18  \
count  445.000000  445.000000  445.000000  ...  445.000000  445.000000   
mean   -78.045765   -0.009056    8.020422  ...   -0.010421    5.929818   
std     13.529565    0.004908   53.184173  ...    0.009772   81.197676   
min   -132.700016   -0.031167  -79.339886  ...   -0.039926 -111.115723   
25%    -85.547909   -0.011338  -40.568447  ...   -0.015478  -77.621841   
50%    -78.077307   -0.008798   -1.403332  ...   -0.008011   -2.831268   
75%    -69.726985   -0.006711   59.408684  ...   -0.004834   85.998573   
max    -32.930338    0.020638  106.178398  ...    0.058948  131.476479   

              y18         z18         x19         y19         z19         x20  \
count  445.000000  445.000000  445.000000  445.000000  445.000000  445.000000   
mean    15.479439   -0.012271    7.422724   13.338474   -0.009722    4.538967   
std     22.092415    0.011206   67.088300   20.354129    0.011031   55.880094   
min    -78.880441   -0.043528  -97.881203  -94.845400   -0.041516  -82.472134   
25%      1.093955   -0.017805  -61.305485   -0.262384   -0.016179  -52.006302   
50%     17.774870   -0.010222    4.035187   15.704763   -0.007807    3.843842   
75%     30.712109   -0.007227   73.123741   27.398186   -0.004841   60.470581   
max     96.435349    0.079197  111.330414   76.134932    0.082467   89.479866   

              y20         z20  
count  445.000000  445.000000  
mean    11.083493   -0.007746  
std     17.953016    0.011026  
min    -97.524605   -0.041118  
25%      0.051177   -0.014817  
50%     13.429821   -0.005316  
75%     23.452699   -0.002505  
max     65.524263    0.081658  

[8 rows x 63 columns]

In [57]:
df_başla.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 445 entries, 0 to 444
Data columns (total 64 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   frame   445 non-null    object 
 1   x0      445 non-null    float64
 2   y0      445 non-null    float64
 3   z0      445 non-null    float64
 4   x1      445 non-null    float64
 5   y1      445 non-null    float64
 6   z1      445 non-null    float64
 7   x2      445 non-null    float64
 8   y2      445 non-null    float64
 9   z2      445 non-null    float64
 10  x3      445 non-null    float64
 11  y3      445 non-null    float64
 12  z3      445 non-null    float64
 13  x4      445 non-null    float64
 14  y4      445 non-null    float64
 15  z4      445 non-null    float64
 16  x5      445 non-null    float64
 17  y5      445 non-null    float64
 18  z5      445 non-null    float64
 19  x6      445 non-null    float64
 20  y6      445 non-null    float64
 21  z6      445 non-null    float64
 22  x7

In [58]:
df_başla.columns

Index(['frame', 'x0', 'y0', 'z0', 'x1', 'y1', 'z1', 'x2', 'y2', 'z2', 'x3',
       'y3', 'z3', 'x4', 'y4', 'z4', 'x5', 'y5', 'z5', 'x6', 'y6', 'z6', 'x7',
       'y7', 'z7', 'x8', 'y8', 'z8', 'x9', 'y9', 'z9', 'x10', 'y10', 'z10',
       'x11', 'y11', 'z11', 'x12', 'y12', 'z12', 'x13', 'y13', 'z13', 'x14',
       'y14', 'z14', 'x15', 'y15', 'z15', 'x16', 'y16', 'z16', 'x17', 'y17',
       'z17', 'x18', 'y18', 'z18', 'x19', 'y19', 'z19', 'x20', 'y20', 'z20'],
      dtype='object')

In [59]:
# Verilere sınıf isimleri verilip kaydedilir

In [60]:
df_başla["hareket_tipi"] = "başla"

In [61]:
df_başla.head()

frame   x0   y0   z0         x1         y1        z1         x2  \
0    frame_0.jpg  0.0  0.0  0.0  20.921745 -32.013216 -0.004908  63.702908   
1    frame_1.jpg  0.0  0.0  0.0  25.215855 -33.129122 -0.005567  70.546875   
2   frame_10.jpg  0.0  0.0  0.0  21.059303 -51.856520 -0.004809  39.689026   
3  frame_100.jpg  0.0  0.0  0.0  20.542946 -48.255172 -0.003943  50.350914   
4  frame_101.jpg  0.0  0.0  0.0  21.442451 -48.781872 -0.003678  51.380196   

           y2        z2  ...        x18        y18       z18        x19  \
0  -63.090448 -0.011111  ...  85.430202  36.061184 -0.031815  69.083805   
1  -60.488298 -0.012280  ...  89.014263  45.146148 -0.031010  72.302513   
2 -102.589860 -0.008057  ...  59.080753 -18.782566 -0.019961  47.803574   
3  -82.153358 -0.008138  ...  98.735275  31.494176 -0.005686  88.978386   
4  -82.783248 -0.007359  ...  99.460602  28.227761 -0.003660  90.144081   

         y19       z19        x20        y20       z20  hareket_tipi  
0  34.941480 -0.025963  46.978397  30.403762 -0.022198         başla  
1  41.144013 -0.025329  50.641079  34.783959 -0.021769         başla  
2 -15.707209 -0.017838  31.267262 -13.266506 -0.017717         başla  
3  26.162224 -0.001247  77.652740  24.368598  0.001567         başla  
4  22.974086  0.000873  78.666000  22.793262  0.003747         başla  

[5 rows x 65 columns]

In [62]:
df_başla.drop("frame",axis=1,inplace=True)

In [63]:
df_başla

x0   y0   z0         x1         y1        z1         x2          y2  \
0    0.0  0.0  0.0  20.921745 -32.013216 -0.004908  63.702908  -63.090448   
1    0.0  0.0  0.0  25.215855 -33.129122 -0.005567  70.546875  -60.488298   
2    0.0  0.0  0.0  21.059303 -51.856520 -0.004809  39.689026 -102.589860   
3    0.0  0.0  0.0  20.542946 -48.255172 -0.003943  50.350914  -82.153358   
4    0.0  0.0  0.0  21.442451 -48.781872 -0.003678  51.380196  -82.783248   
..   ...  ...  ...        ...        ...       ...        ...         ...   
440  0.0  0.0  0.0  20.546837 -38.334324 -0.004657  55.080528  -81.272092   
441  0.0  0.0  0.0  23.184814 -40.428572 -0.003791  56.957359  -82.403576   
442  0.0  0.0  0.0  22.280273 -42.115595 -0.003923  55.857124  -83.085608   
443  0.0  0.0  0.0  22.844925 -42.009766 -0.004190  55.487938  -79.160593   
444  0.0  0.0  0.0  19.901161 -46.715691 -0.005099  50.059090  -81.976333   

           z2          x3  ...         x18        y18       z18        x19  \
0   -0.011111   97.753887  ...   85.430202  36.061184 -0.031815  69.083805   
1   -0.012280  106.178398  ...   89.014263  45.146148 -0.031010  72.302513   
2   -0.008057   45.043831  ...   59.080753 -18.782566 -0.019961  47.803574   
3   -0.008138   79.851151  ...   98.735275  31.494176 -0.005686  88.978386   
4   -0.007359   80.974617  ...   99.460602  28.227761 -0.003660  90.144081   
..        ...         ...  ...         ...        ...       ...        ...   
440 -0.010403   75.057793  ...  107.309990  27.578495 -0.021592  90.226936   
441 -0.010255   76.807823  ...  106.568184  30.059946 -0.022523  89.734154   
442 -0.009499   77.582588  ...  108.267059  32.785563 -0.017732  92.640381   
443 -0.009657   79.153404  ...  106.813660  38.229783 -0.017000  92.088203   
444 -0.010073   76.804733  ...   99.607658  34.651930 -0.010072  89.122696   

           y19       z19        x20        y20       z20  hareket_tipi  
0    34.941480 -0.025963  46.978397  30.403762 -0.022198         başla  
1    41.144013 -0.025329  50.641079  34.783959 -0.021769         başla  
2   -15.707209 -0.017838  31.267262 -13.266506 -0.017717         başla  
3    26.162224 -0.001247  77.652740  24.368598  0.001567         başla  
4    22.974086  0.000873  78.666000  22.793262  0.003747         başla  
..         ...       ...        ...        ...       ...           ...  
440  26.246231 -0.015868  69.959335  21.158059 -0.012244         başla  
441  27.300467 -0.016260  69.970665  22.698891 -0.012271         başla  
442  28.608270 -0.011782  74.571533  25.817378 -0.007863         başla  
443  32.675679 -0.011029  75.491867  30.705092 -0.007166         başla  
444  27.535172 -0.005223  76.243286  26.192286 -0.002003         başla  

[445 rows x 64 columns]

In [64]:
df_dur["hareket_tipi"] = "dur"
df_geri["hareket_tipi"] = "geri"
df_ileri["hareket_tipi"] = "ileri"

In [65]:
df_dur.drop("frame",axis=1,inplace=True)
df_geri.drop("frame",axis=1,inplace=True)
df_ileri.drop("frame",axis=1,inplace=True)

In [66]:
df_dur.head()

x0   y0   z0         x1         y1        z1         x2         y2  \
0  0.0  0.0  0.0  41.548576 -33.674587 -0.011432  63.121605 -80.786687   
1  0.0  0.0  0.0  43.027210 -32.051647 -0.011470  64.644241 -81.841439   
2  0.0  0.0  0.0  37.817001 -28.894215 -0.009417  56.425667 -70.278404   
3  0.0  0.0  0.0  26.236496 -22.163887 -0.005464  41.856480 -47.872571   
4  0.0  0.0  0.0  25.381622 -23.199842 -0.005241  41.845322 -48.546878   

         z2         x3  ...        x18         y18       z18         x19  \
0 -0.015635  66.863823  ... -94.093323 -134.060154 -0.028112 -110.774574   
1 -0.015047  67.557621  ... -87.546215 -130.867510 -0.025316 -103.371792   
2 -0.012622  60.545311  ... -78.596706 -110.894687 -0.020997  -93.066788   
3 -0.007540  46.493683  ... -54.091759  -73.820239 -0.011784  -62.229023   
4 -0.007601  49.171600  ... -57.741566  -72.142807 -0.013412  -67.368793   

          y19       z19         x20         y20       z20  hareket_tipi  
0 -160.467253 -0.033516 -124.373817 -184.918860 -0.036496           dur  
1 -156.064847 -0.030341 -116.096478 -180.115314 -0.033192           dur  
2 -132.833204 -0.025098 -103.802776 -153.470485 -0.027234           dur  
3  -88.634176 -0.013634  -68.131199 -102.862254 -0.014813           dur  
4  -86.836077 -0.015285  -74.357071 -101.198663 -0.016453           dur  

[5 rows x 64 columns]

In [67]:
df_geri.head()

x0   y0   z0         x1         y1        z1         x2         y2  \
0  0.0  0.0  0.0  23.907509 -58.763037 -0.007186  71.213150 -93.438978   
1  0.0  0.0  0.0  23.002052 -58.518934 -0.007278  67.829590 -90.724626   
2  0.0  0.0  0.0  12.116432 -54.896085 -0.006789  44.234505 -89.536171   
3  0.0  0.0  0.0  10.893631 -39.555609 -0.001364  39.416313 -61.393447   
4  0.0  0.0  0.0  11.498680 -40.976000 -0.001891  39.224396 -63.079344   

         z2          x3  ...         x18        y18       z18         x19  \
0 -0.012575  116.988258  ...  151.229553  72.163053 -0.023793  181.762390   
1 -0.012802  111.678429  ...  145.195084  71.557753 -0.023194  174.038544   
2 -0.011322   78.678131  ...  130.667610  46.975179 -0.015290  156.333733   
3 -0.002103   70.636940  ...   98.156319  23.284814 -0.005520  113.414154   
4 -0.002568   69.343643  ...   92.093353  25.287845 -0.002981  104.670982   

         y19       z19         x20        y20       z20  hareket_tipi  
0  81.262050 -0.024991  208.386269  87.047253 -0.025336          geri  
1  81.143217 -0.024374  198.650093  87.538741 -0.024620          geri  
2  53.143787 -0.016223  177.897148  58.290346 -0.016127          geri  
3  23.827543 -0.003916  123.842812  23.927515 -0.002576          geri  
4  25.160322 -0.001145  112.889214  24.723487  0.000268          geri  

[5 rows x 64 columns]

In [68]:
df_ileri.head()

x0   y0   z0         x1         y1        z1         x2         y2  \
0  0.0  0.0  0.0 -12.470226 -46.172318 -0.012521 -42.986813 -81.280975   
1  0.0  0.0  0.0 -12.532482 -46.345224 -0.011949 -41.901054 -80.204272   
2  0.0  0.0  0.0 -10.791149 -42.641716 -0.009957 -38.911858 -73.375196   
3  0.0  0.0  0.0 -20.560684 -37.279122 -0.009104 -61.048164 -59.170389   
4  0.0  0.0  0.0 -17.866058 -36.705108 -0.009697 -56.286850 -57.994552   

         z2          x3  ...         x18        y18       z18         x19  \
0 -0.018105  -77.442112  ... -140.114365  44.861426 -0.025771 -166.031113   
1 -0.017286  -74.822617  ... -138.731804  43.731101 -0.024121 -164.337959   
2 -0.014764  -69.305878  ... -123.277760  48.655250 -0.020713 -146.186199   
3 -0.011856 -100.275650  ... -117.729378  35.505259 -0.016214 -139.599495   
4 -0.013235  -94.673424  ... -110.900345  43.483071 -0.019814 -132.336273   

         y19       z19         x20        y20       z20  hareket_tipi  
0  54.166932 -0.031358 -189.296894  60.920949 -0.034530         ileri  
1  52.411866 -0.029248 -187.176189  58.558459 -0.032074         ileri  
2  56.765091 -0.024676 -166.449795  62.533300 -0.026763         ileri  
3  35.750649 -0.018989 -160.068970  35.756443 -0.020417         ileri  
4  46.080651 -0.023220 -152.296143  46.802659 -0.024917         ileri  

[5 rows x 64 columns]

In [69]:
# Sıralı olan verileri modelin daha iyi öğrenmesi için rastgele karıştırız

In [70]:
from sklearn.utils import shuffle

In [71]:
df_dur_shuffled = shuffle(df_dur, random_state=15)
df_başla_shuffled = shuffle(df_başla, random_state=15)
df_geri_shuffed = shuffle(df_geri, random_state=15)
df_ileri_shuffled = shuffle(df_ileri, random_state=15)

In [72]:
# Tüm veriler df de toplanır ve tekrar karıştırılır

In [73]:
df = pd.concat([df_ileri_shuffled,df_başla_shuffled,df_dur_shuffled,df_geri_shuffed], ignore_index=True)
df["hareket_tipi"].unique()

array(['ileri', 'başla', 'dur', 'geri'], dtype=object)

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1792 entries, 0 to 1791
Data columns (total 64 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   x0            1792 non-null   float64
 1   y0            1792 non-null   float64
 2   z0            1792 non-null   float64
 3   x1            1792 non-null   float64
 4   y1            1792 non-null   float64
 5   z1            1792 non-null   float64
 6   x2            1792 non-null   float64
 7   y2            1792 non-null   float64
 8   z2            1792 non-null   float64
 9   x3            1792 non-null   float64
 10  y3            1792 non-null   float64
 11  z3            1792 non-null   float64
 12  x4            1792 non-null   float64
 13  y4            1792 non-null   float64
 14  z4            1792 non-null   float64
 15  x5            1792 non-null   float64
 16  y5            1792 non-null   float64
 17  z5            1792 non-null   float64
 18  x6            1792 non-null 

In [75]:
df = shuffle(df,random_state=15)

In [76]:
df.head()

x0   y0   z0         x1         y1        z1         x2         y2  \
1022  0.0  0.0  0.0  26.277065 -23.754351 -0.005228  41.564484 -53.283702   
471   0.0  0.0  0.0  -2.213287 -37.588370 -0.009398 -20.904036 -73.775339   
1251  0.0  0.0  0.0  39.443436 -35.387585 -0.006280  56.792965 -80.868409   
1169  0.0  0.0  0.0  29.475403 -26.932318 -0.008224  50.586090 -59.637222   
757   0.0  0.0  0.0  -0.508919 -42.162105 -0.005274 -14.429455 -84.368820   

            z2         x3  ...        x18         y18       z18        x19  \
1022 -0.006808  46.176968  ... -44.497547  -90.274336 -0.009855 -47.098217   
471  -0.013873 -39.976616  ... -87.604780   12.831795 -0.008293 -67.455654   
1251 -0.007976  55.351696  ... -81.320057 -126.441640 -0.016727 -92.041798   
1169 -0.012125  59.681969  ... -71.580963  -97.101288 -0.020246 -84.080257   
757  -0.008000 -26.246738  ... -74.862270   -9.262247 -0.012568 -56.403465   

             y19       z19         x20         y20       z20  hareket_tipi  
1022 -107.219921 -0.011096  -47.756081 -122.987899 -0.011833           dur  
471    13.039269 -0.006067  -55.280628    9.262762 -0.002638         başla  
1251 -149.348874 -0.019369 -101.562595 -169.342811 -0.020898           dur  
1169 -115.510812 -0.023297  -93.322220 -131.921200 -0.024935           dur  
757    -7.459738 -0.010298  -50.743504   -4.539006 -0.008189         başla  

[5 rows x 64 columns]

In [77]:
df.tail()

x0   y0   z0         x1         y1        z1         x2         y2  \
156   0.0  0.0  0.0 -16.532593 -39.320068 -0.010924 -52.879715 -63.786771   
384   0.0  0.0  0.0 -10.504475 -35.373616 -0.008780 -34.912033 -64.642868   
645   0.0  0.0  0.0   2.070522 -43.123773 -0.005665 -11.589146 -84.835348   
1781  0.0  0.0  0.0  18.354836 -46.821134 -0.002055  53.439102 -67.929497   
1480  0.0  0.0  0.0  -7.169609 -38.465420  0.000629  10.273705 -65.825690   

            z2         x3  ...         x18        y18       z18         x19  \
156  -0.014953 -90.602760  ... -105.124741  56.071665 -0.021622 -123.918800   
384  -0.013174 -60.443344  ... -112.824669  39.146261 -0.019792 -132.997513   
645  -0.007779 -29.880638  ...  -90.024204 -15.629575 -0.006463  -70.264835   
1781 -0.003473  91.435547  ...  120.570030  29.260368 -0.006795  141.921959   
1480  0.002493  34.540558  ...   90.487518 -17.403020  0.005884   98.386459   

            y19       z19         x20        y20       z20  hareket_tipi  
156   66.835735 -0.025966 -142.626228  75.291195 -0.028444         ileri  
384   47.489712 -0.023131 -151.458149  53.434689 -0.024905         ileri  
645  -15.098723 -0.003447  -58.606052  -9.417740 -0.000128         başla  
1781  28.107190 -0.005730  158.429604  26.080213 -0.004605          geri  
1480 -23.207181  0.007961  101.962738 -27.653875  0.009477          geri  

[5 rows x 64 columns]

In [78]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df["hareket_tipi_encoded"] = encoder.fit_transform(df["hareket_tipi"])
df.drop("hareket_tipi", axis=1, inplace=True)


In [79]:
df.head()

x0   y0   z0         x1         y1        z1         x2         y2  \
1022  0.0  0.0  0.0  26.277065 -23.754351 -0.005228  41.564484 -53.283702   
471   0.0  0.0  0.0  -2.213287 -37.588370 -0.009398 -20.904036 -73.775339   
1251  0.0  0.0  0.0  39.443436 -35.387585 -0.006280  56.792965 -80.868409   
1169  0.0  0.0  0.0  29.475403 -26.932318 -0.008224  50.586090 -59.637222   
757   0.0  0.0  0.0  -0.508919 -42.162105 -0.005274 -14.429455 -84.368820   

            z2         x3  ...        x18         y18       z18        x19  \
1022 -0.006808  46.176968  ... -44.497547  -90.274336 -0.009855 -47.098217   
471  -0.013873 -39.976616  ... -87.604780   12.831795 -0.008293 -67.455654   
1251 -0.007976  55.351696  ... -81.320057 -126.441640 -0.016727 -92.041798   
1169 -0.012125  59.681969  ... -71.580963  -97.101288 -0.020246 -84.080257   
757  -0.008000 -26.246738  ... -74.862270   -9.262247 -0.012568 -56.403465   

             y19       z19         x20         y20       z20  \
1022 -107.219921 -0.011096  -47.756081 -122.987899 -0.011833   
471    13.039269 -0.006067  -55.280628    9.262762 -0.002638   
1251 -149.348874 -0.019369 -101.562595 -169.342811 -0.020898   
1169 -115.510812 -0.023297  -93.322220 -131.921200 -0.024935   
757    -7.459738 -0.010298  -50.743504   -4.539006 -0.008189   

      hareket_tipi_encoded  
1022                     1  
471                      0  
1251                     1  
1169                     1  
757                      0  

[5 rows x 64 columns]

In [80]:
df.tail()

x0   y0   z0         x1         y1        z1         x2         y2  \
156   0.0  0.0  0.0 -16.532593 -39.320068 -0.010924 -52.879715 -63.786771   
384   0.0  0.0  0.0 -10.504475 -35.373616 -0.008780 -34.912033 -64.642868   
645   0.0  0.0  0.0   2.070522 -43.123773 -0.005665 -11.589146 -84.835348   
1781  0.0  0.0  0.0  18.354836 -46.821134 -0.002055  53.439102 -67.929497   
1480  0.0  0.0  0.0  -7.169609 -38.465420  0.000629  10.273705 -65.825690   

            z2         x3  ...         x18        y18       z18         x19  \
156  -0.014953 -90.602760  ... -105.124741  56.071665 -0.021622 -123.918800   
384  -0.013174 -60.443344  ... -112.824669  39.146261 -0.019792 -132.997513   
645  -0.007779 -29.880638  ...  -90.024204 -15.629575 -0.006463  -70.264835   
1781 -0.003473  91.435547  ...  120.570030  29.260368 -0.006795  141.921959   
1480  0.002493  34.540558  ...   90.487518 -17.403020  0.005884   98.386459   

            y19       z19         x20        y20       z20  \
156   66.835735 -0.025966 -142.626228  75.291195 -0.028444   
384   47.489712 -0.023131 -151.458149  53.434689 -0.024905   
645  -15.098723 -0.003447  -58.606052  -9.417740 -0.000128   
1781  28.107190 -0.005730  158.429604  26.080213 -0.004605   
1480 -23.207181  0.007961  101.962738 -27.653875  0.009477   

      hareket_tipi_encoded  
156                      3  
384                      3  
645                      0  
1781                     2  
1480                     2  

[5 rows x 64 columns]

In [81]:
df["hareket_tipi_encoded"].unique()

array([1, 0, 3, 2])

In [82]:
# model eğitimi

In [83]:
from sklearn.model_selection import train_test_split
X = df.drop("hareket_tipi_encoded",axis=1)
y = df["hareket_tipi_encoded"]
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=15, test_size=0.3)

In [84]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [85]:
X_train

array([[ 0.        ,  0.        ,  0.        , ..., -1.10091195,
        -2.09414101, -1.32711107],
       [ 0.        ,  0.        ,  0.        , ...,  1.51082858,
         0.63935181, -0.83308273],
       [ 0.        ,  0.        ,  0.        , ..., -0.67432651,
        -1.4976225 , -1.35324004],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.46721806,
         0.39269012,  1.01150684],
       [ 0.        ,  0.        ,  0.        , ..., -0.41789846,
        -1.59957207, -0.23060155],
       [ 0.        ,  0.        ,  0.        , ..., -1.35063937,
         0.85366515, -0.37897317]])

In [86]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(y_pred)

[0 2 1 1 0 1 1 0 1 2 1 2 3 0 0 2 0 1 3 3 1 3 1 1 0 3 3 2 1 2 3 0 2 1 1 1 2
 1 1 0 2 2 3 3 1 3 3 1 3 0 1 3 0 1 1 3 1 2 3 0 1 2 1 0 2 2 2 3 1 3 2 0 1 2
 2 3 0 0 3 1 1 0 0 1 1 2 3 0 1 1 3 3 1 0 2 1 2 1 0 0 0 1 3 3 3 2 2 2 0 0 1
 1 0 3 2 1 3 0 3 0 1 3 0 2 1 1 3 1 2 1 2 3 0 2 2 2 3 3 1 0 3 1 3 0 2 3 0 3
 3 3 3 3 2 2 0 3 3 0 0 3 3 1 2 3 3 2 1 1 2 3 2 2 0 1 0 1 1 0 1 1 3 0 1 0 2
 0 2 2 2 1 0 1 2 1 3 3 2 3 1 0 1 0 3 0 0 1 3 1 1 1 3 3 0 3 0 1 3 2 3 2 0 1
 3 1 0 2 0 2 1 0 0 0 3 3 3 1 3 0 0 2 3 0 3 1 2 2 0 1 2 0 3 1 0 1 2 1 1 0 1
 2 0 3 2 2 2 2 2 2 2 3 3 2 0 2 1 2 3 1 0 2 2 2 2 2 0 1 3 3 1 0 0 1 2 2 0 3
 0 2 0 1 1 3 0 0 3 2 0 3 3 1 1 0 2 3 2 0 2 3 1 0 3 3 1 1 2 0 0 2 3 3 2 1 2
 1 1 2 2 0 2 2 3 1 0 0 1 1 1 2 3 2 0 2 2 2 0 3 2 2 1 2 3 3 2 0 3 2 3 2 2 3
 1 0 2 3 0 3 1 3 1 3 2 0 1 1 2 3 3 0 1 3 1 1 2 1 1 2 1 3 1 3 0 0 2 3 0 3 2
 3 2 1 0 2 1 0 2 3 3 1 3 2 3 1 0 1 2 2 2 2 0 0 3 2 1 0 0 3 1 0 1 2 3 1 0 2
 2 0 0 1 2 1 3 3 3 2 1 0 0 1 1 1 0 0 3 3 1 0 3 1 1 2 0 2 1 0 0 1 0 2 1 2 1
 3 3 2 2 2 3 3 1 2 2 2 0 

In [87]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [88]:
score = accuracy_score(y_pred,y_test)
print("score: ",score)
print(classification_report(y_pred,y_test))
print("matris\n",confusion_matrix(y_pred,y_test))

score:  1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       121
           1       1.00      1.00      1.00       144
           2       1.00      1.00      1.00       140
           3       1.00      1.00      1.00       133

    accuracy                           1.00       538
   macro avg       1.00      1.00      1.00       538
weighted avg       1.00      1.00      1.00       538

matris
 [[121   0   0   0]
 [  0 144   0   0]
 [  0   0 140   0]
 [  0   0   0 133]]


In [89]:
#model = LogisticRegression()

In [90]:
#penalty = ["l1","l2","elasticnet"]

In [91]:
#c_values = [100, 10, 1, 0.1, 0.01]

In [92]:
#solver = ["newton-cg", "lbfgs", "liblinear", "saga", "newton-cholesky"]

In [93]:
#params = dict(penalty=penalty, C=c_values, solver=solver)

In [94]:
#from sklearn.model_selection import GridSearchCV, StratifiedKFold

In [95]:
#cv = StratifiedKFold()

In [96]:
#grid = GridSearchCV(estimator=model, param_grid=params, cv=cv, scoring="accuracy", n_jobs=-1)

In [97]:
#grid.fit(X_train,y_train)

In [98]:
#grid.best_params_

In [99]:
#grid.best_score_

In [100]:
#y_pred = grid.predict(X_test)

In [101]:
#score = accuracy_score(y_pred,y_test)
print("score: ",score)
print(classification_report(y_pred,y_test))
print("matris\n",confusion_matrix(y_pred,y_test))

score:  1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       121
           1       1.00      1.00      1.00       144
           2       1.00      1.00      1.00       140
           3       1.00      1.00      1.00       133

    accuracy                           1.00       538
   macro avg       1.00      1.00      1.00       538
weighted avg       1.00      1.00      1.00       538

matris
 [[121   0   0   0]
 [  0 144   0   0]
 [  0   0 140   0]
 [  0   0   0 133]]


In [102]:
import pickle

In [103]:
with open("logistic_model.pkl", "wb") as f:
    pickle.dump(model, f)

In [104]:
with open("scaler_model.pkl", "wb") as f:
    pickle.dump(scaler, f)